# Use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy only the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install app dependencies (only if package files have changed)
RUN npm install --production

# Copy only necessary application files to the working directory
COPY app.js .

# Expose port 5000
EXPOSE 5000

# Command to run the application
CMD ["node", "app.js"]
